### ISSUE TITLE
SAPAuthentication Module + Deeplink doesn't seem to work

### ISSUE THREAD

**Issue by aleworth** [mendix/DeeplinkModule#19]
We're experiencing an issue where when we use the LoginLocation constant pointing at our 'login-with-sso.html' page and 'Allow guests' checked off for the deep link configuration, the deep link fails.
However, the minute we turn 'Allow guests' on it works fine, but there is no SSO that takes place. Is this the same for others using the XSUAA Authentication module from the app store along with deep links?

**Comment by Robinfr** [comment]
Closed because of inactivity.
