### ISSUE TITLE
Deeplink is no longer followed after forced login

### ISSUE THREAD

**Issue by JarnoKoopman** [mendix/DeeplinkModule#31]
Hi,

I have been using the deep link module since the start of the project but ever since the update, i cannot get the following scenario te work, which was always fine:

1. User goes to a deeplink that requires a logged in user
2. In the old version, i had a specific login.html in the resources/deeplink which allowed a user to login but keep the URL in the bar
3. In this version, it is replace with a theme/login.html but that just leads ppl to the default MF/page after login
4. If they follow the deeplink while logged in, it works fine

Please assist because i cannot follow what exactly was changed thats causing this to function like this?

**Comment by Robinfr** [comment]
Have you set the constant: `DeepLink.LoginLocation`?

**Comment by BrigthA** [comment]
I have set the login location. but still, it is not redirecting to the respective page, but it is redirecting to the login page.

**Comment by Robinfr** [comment]
This should be fixed now when using the latest Mendix version.
