### ISSUE TITLE
SameSite Setting Issue

### ISSUE THREAD

**Issue by phishman93** [mendix/DeeplinkModule#37]
We use 3rd party payment processing that uses the deeplink url we send them as a redirect after the user is done paying. 

This has been working great in the past, and works great when the Mendix runtime setting "SameSite" is set to "None". However, if it's anything else, it seems to create a new, anonymous session on redirect. 

Am I potentially missing another setting somewhere to fix this, or do I have to keep the same site setting as none?

Thanks in advance, 
Jordan

**Comment by Robinfr** [comment]
Hi, by default cookies in Mendix are sent with `SameSite=Strict` meaning they are not sent from other origins than the Mendix app. You could try to set this to `Lax` instead to still benefit from some security, but allow the cookies to be sent as long as you are navigating to the origin URL.

>The strict value will prevent the cookie from being sent by the browser to the target site in all cross-site browsing contexts, even when following a regular link. For example, for a GitHub-like website this would mean that if a logged-in user follows a link to a private GitHub project posted on a corporate discussion forum or email, GitHub will not receive the session cookie and the user will not be able to access the project.

From: https://owasp.org/www-community/SameSite
